### ISSUE TITLE
Package/namespace style only works for single stereotype

### ISSUE THREAD

**Issue by BenceSzalai** [plantuml/plantuml#1260]
See example [here for packages](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuIf8JCvEJ4zLIClFDrImiV7BJqcrirEevb9GICv9B2vMS0QHXborNCWgZO0gNH9B4fCIYx6eDa9MdPHOX30No0XEJSxFIy7KPCnLYwp724afJcUPeEenHd8L7bscgBfCu0hnUieCgCiXDIy566O0) and [here for namespaces](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSfBp4qjBaXCJbL8oyytLB2nySjFIRMpKwZcKb18paaiBbPm1f66NBLSg6gDW6fT4aiIanABiQWtGbMVb5Y4C1l824vDpizBmTHcp5MBgii8IJ5EnvcWwp96SXiUVQRe-apWIl5wpWoepo4rBmKOVW00)

The demo shows that when a package is applied with one of the predefined stereotypes with a specific style associated (as listed [here](https://plantuml.com/en-dark/class-diagram#a05971470d7fd711)) it is indeed rendered with that style, but if any additional stereotypes are added, the rendering switches to the default style. This behaviour is the same regardless if the second stereotype is a custom or a built in one. Also it is the same for namespaces as well.

I think when multiple stereotypes are present, but only one of them has a style associated, that style should be applied, probably regardless or order of the stereotypes being declared. Indeed when multiple styled stereotypes are applied, they cannot be all respected, in that case either the first or the last should take precedence and be applied.

Potentially related to #1254.

**Comment by arnaudroques** [comment]
I think this is solved now.
Please reopen the issue if it is not.

**Comment by BenceSzalai** [comment]
The linked diagrams are still showing the issue. Should the fix be available in the online deployment already?

**Comment by arnaudroques** [comment]
Actually, we should be more precise here.
We would like to remove this feature of using stereotype to change package style.

So [you should use this syntax instead](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuShBJqbLIClFDrIevb9GICv9B2vMS0QHXborN5mfYIM9IOd5O1L6w2gCW2eW-fCIYmmLR6o2KvFpyrBixD0L6YCP1LPiXAGOo0p9o2p2eiq4gCqXDIy5w4m0):

```
@startuml
node foo1 {
  class Class1
}

database foo2 {
  class Class2
}

node bar1 <<Second>> {
  class Class3
}

database bar2 <<Second>> <<Third>> {
  class Class4
}
@enduml
```

So we should probably update the documentation about this.
We are doing so because it simplify and make stereotype use more clear.

Note that we are here because of _historical_ reason: at some point, it was the only way to change package style. But now we have `database`, `node`, ... keywords.

And since we try to not break legacy diagrams, we still are supporting this legacy use of stereotypes, even if we would like users not to use it any more.

Does it help?

**Comment by BenceSzalai** [comment]
It does, however it also confuses me. So when a "group" is declared with a style keyword, such as `database`, `node` etc. would it be a package or a namespace? And if so, how to declare the other one? With the stereotypes it was possible to apply the formatting to both packages and namespaces.

**Comment by arnaudroques** [comment]
> It does, however it also confuses me. 

Sorry, all those concepts have changed recently, so that's why it's confusing.
However, we may have miss something.

> So when a "group" is declared with a style keyword, such as `database`, `node` etc. would it be a package or a namespace?

Yes.

And now, there are no difference between package and namespace. See https://plantuml.com/news.

Let's have a [concrete example](http://www.plantuml.com/plantuml/umla/SoWkIImgAStDuKf9B4bCIYnELO0n31LiR8fBKejIymtjx1IgkHGKalDp2_BpKlDA598DkMgv75BpKe0w0G00):

```
@startuml
database database1 <<stereo1>> {
  component c1
}
@enduml
```

> And if so, how to declare the other one? With the stereotypes it was possible to apply the formatting to both packages and namespaces.

So here I am confused :-)
Which _other_ one ?
Please modify my example so that I better understand. Thanks!

**Comment by BenceSzalai** [comment]
Okay, I got it, package and namespace is now the same thing. I am yet to explore this new approach, so I cannot comment on it any further.

I like this part:
> > would it be a package or a namespace?
>
> Yes.

Thanks. I think we can close it now. If I'll find issues with this I'll let you know in the future!
