### ISSUE TITLE
How to extends a generic class

### ISSUE THREAD

**Issue by traitimtrongvang** [plantuml/plantuml#1672]
I'm concerning that is there a way to extends a generic class?
here is what is try, but it says syntax error, please help me out, thank you so much

![image](https://github.com/plantuml/plantuml/assets/149607882/919e4f41-dc42-489f-ae89-cc1104207034)

**Comment by arnaudroques** [comment]
This is a bug!
Thanks for the report.
This should be [fixed with last snapshot](https://www.plantuml.com/plantuml/uml/SoWkIImgAStDuKhEIImkLd1AB4vrpaWiiN6qKqYjA4dDIu68kUQLP9PKAbHprN91LJhdbnRaWDKY528qGrGw08M1PWC0).

**Comment by traitimtrongvang** [comment]
hi @arnaudroques 
I'm using plantuml  jetbrains plugin, my IDE is WriteSide and I see the issue is still happening even after updating the plantuml plugin

![image](https://github.com/plantuml/plantuml/assets/149607882/1f391ffc-a1de-4880-b56c-30daa74e4b84)
![image](https://github.com/plantuml/plantuml/assets/149607882/815a20b3-b6eb-4c0b-bae0-e22d9658389b)

I hope you guy can fix this soon, thank you.

**Comment by The-Lum** [comment]
Hello @traitimtrongvang,

In fact this is currently only fixed on [_snapshot or pre-release_](https://github.com/plantuml/plantuml/releases/tag/snapshot).
You must awaiting the new [release](https://github.com/plantuml/plantuml/releases) or perhaps update your plugin with the snapshot version.

_If that can help_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

This is now done, with the last [release `v1.2024.4`](https://github.com/plantuml/plantuml/releases/tag/v1.2024.4):
- Thanks @traitimtrongvang  for the report.
- Thanks PlantUML team for your work.

Regards.
