### ISSUE TITLE
After v1.2023.10, Remove command does not remove nested shapes

### ISSUE THREAD

**Issue by JohnLeyva** [plantuml/plantuml#1769]
**Describe the bug**
removing a nested shape stopped working.

Stopped working after
docker.io/plantuml/plantuml-server:jetty-v1.2023.10

**To Reproduce**
Use the code indicated

![image](https://github.com/plantuml/plantuml/assets/1241530/f97b1857-bb2a-410b-89b4-7ddde4fbe16c)

```
@startuml
frame f1 {
   component A
}
component B

' DOES NOT WORK
remove A

'works
remove B

'works
' remove f1  


@enduml
```

https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKehIinDLKWpLAZcKb1GICxFBSZFIyqhKN3agkL2y9oukDGLNFnTWnNy_4CKmls3lBcAKdFpor8L784ovVb5sSKm0IUO0507M0XikW8N5vT3QbuAq4e0

**Comment by JohnLeyva** [comment]
Thanks @The-Lum for reviewing the bug. 
From my POV  show / remove / hide is a very useful feature.

**Comment by arnaudroques** [comment]
Thanks for the report.
This should be [fixed in last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

**Comment by JohnLeyva** [comment]
Looks like it is still not fixed yet

![image](https://github.com/user-attachments/assets/cfa0c405-816e-487f-b345-eeb2f2bd3bd7)


Just tried in 
https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000

https://www.plantuml.com/plantuml/png/SoWkIImgAStDuIh9BCb9LL0jIoqgpipFqz3auaehIinDLKWpLAZcKb1GICxFBSZFIyqhKN3agkL2y9oukDGLNFnTWnNy_4CKmls3lBcAKdFpoq0wzHnnoJa2TPNd5sKNmmISO0907N3z2WfSN5mEgNafG0S20000


```
@startuml
title %version()

frame f1 {
   component A
}
component B

' DOES NOT WORK
remove f1.A
' DOES NOT WORK
remove A

'works
remove B

'works
' remove f1  

@enduml
```

**Comment by The-Lum** [comment]
Hi @JohnLeyva 

- Could you test on `v1.2024.7`?
_It is now fixed._

And FYI, the `remove f1.A` seems to be now only for class diagram.
	
_Enjoy,_
Regards,
Th.

**Comment by JohnLeyva** [comment]
Works with shapes at nesting level 0 or 1.
Fails when a shape is at nesting level 2 or deeper  ( in  the example Components C, D )

![image](https://github.com/user-attachments/assets/02f6be0b-53b6-455d-ae6d-68c29286cdd3)


```
@startuml

title %version()

component A
frame l1 {
   component B
   frame l2 {
      component C
      frame l3 {
         component D
      }
   }
}

' DOES NOT WORK 
remove C
remove D

@enduml
```

**Comment by DrMarkusVoss** [comment]
This is an essential feature for creating re-usable elements. I make heavy use of this feature for

https://github.com/DrMarkusVoss/pumla

I posted a similar example in the forum as I just recently learned about this bug:

https://forum.plantuml.net/19823/allowmixing-has-side-effect-on-remove

It seems to have a relation to the mixing of class/object elements with other elements (see my answer and example on the post above).

**Comment by The-Lum** [comment]
Hi @DrMarkusVoss 

>I posted a similar example in the forum as I just recently learned about this bug

See my answer with:
> Same answer as:
>- https://forum.plantuml.net/19823/allowmixing-has-side-effect-on-remove?show=19843#c19843
>
>If you use `allowmixing` and potentially class and namespace...
>
>To remove/hide, you must use:
>- `set separator none`
>- or explicitly the full namespace, like `remove huhu.trara`

_Enjoy,_
Regards,
Th.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed on [v1.2024.8](https://github.com/plantuml/plantuml/releases/tag/v1.2024.8).

- Thanks @JohnLeyva for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.
