### ISSUE TITLE
activity diagram (beta) on error when adding fork or split under a if statement that contains a break

### ISSUE THREAD

**Issue by kasra0** [plantuml/plantuml#399]
Hi,
i have this activity diagram 

```
@startuml
start
   repeat 
   if(condition A) then (yes)
    fork
   :a1;
    fork again
   :a2;
   end fork
   elseif(condition B) then (yes)
    :b1;
    :b2;
   elseif(condition C) then (yes)
   -[#blue]->
   break   
   endif
   repeat while(test) is (No) not (Yes)
 end
@enduml
```

It seams that we can't add a split or a fork in that case. 
If we take away the fork statement no error occurs.

Is that  a normal behaviour or we should be able doing that ?

i attached the error stack.
thanks for your help.

![error](https://user-images.githubusercontent.com/16036382/97780997-aacd1000-1b88-11eb-8669-9b2fd0d7667a.png)

**Comment by arnaudroques** [comment]
Thanks for the report.
This has been fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if you find other issues!

**Comment by kasra0** [comment]
Thanks for your reactivity.
Everything works perfectly now.

**Comment by kasra0** [comment]
Oops i am sorry i reopened the issue because it does work now with **fork** but we still have the issue with **split**
Exemple 

```
@startuml
start
   repeat 
   if(condition A) then (yes)
    split
   :a1;
    split again
   :a2;
   end split
   elseif(condition B) then (yes)    
    :b1;  
    :b2; 
   elseif(condition C) then (yes)
   -[#blue]->
   break   
   endif
   repeat while(test) is (No) not (Yes)
 end
@enduml
```
thanks.

![error-plantuml](https://user-images.githubusercontent.com/16036382/97974613-1fda5880-1dc8-11eb-9e6b-90005e54be73.png)

**Comment by arnaudroques** [comment]
The crash is fixed in last beta http://beta.plantuml.net/plantuml.jar
The drawing is not perfect, and this one is not that easy to solve...

**Comment by kasra0** [comment]
I just tested and both cases work  :+1:

Even if the drawing is not perfect at least we can now express these types of structure.

Thanks a lot Arnaud !!
