### ISSUE TITLE
Network diagram (nwdiag) doesn't support hostname with hyphen (-) or dot (.)

### ISSUE THREAD

**Issue by doczkal** [plantuml/plantuml#827]
I noticed that a hostname like "web-01.example.com" leads to an error.
Actually two errors have to be resolved here.

- Hostnames in plantUML can't have hyphens (-)
- Hostnames in plantUML can't have dots (.)

Yes I had to search longer then expected, but I found the proof that dot and hyphen are valid characters here:
https://www.ietf.org/rfc/rfc1034.txt

minimal example:
```
@startuml
nwdiag {
	network internal {
	address = "192.168.40.0/24";
	web-01.example.com [address = "192.168.40.2"];
}
@enduml
```

**Comment by The-Lum** [comment]
Hello @doczkal,

For that _(a possible workaround)_, you can use `description`, as:
```puml
@startuml
nwdiag {
	network internal {
	address = "192.168.40.0/24";
	web01 [description = "web-01.example.com" address = "192.168.40.2"];
}
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/RSx12W8X4CRny_eKW_TCboMA9TZtY0ws3Y7fk8mJ1j6xP_UkFpu-_aiLp_BCIL4BqT_XhGP2QOKV44cGoQUV-H0OQuKpQ7SQZJiSpMIDtO-JdjNGy6OTN0BMbUCciL3VTTnPP_3byvRGh2Lh-7ypwkkiFcf12hta2m00)](http://www.plantuml.com/plantuml/uml/RSx12W8X4CRny_eKW_TCboMA9TZtY0ws3Y7fk8mJ1j6xP_UkFpu-_aiLp_BCIL4BqT_XhGP2QOKV44cGoQUV-H0OQuKpQ7SQZJiSpMIDtO-JdjNGy6OTN0BMbUCciL3VTTnPP_3byvRGh2Lh-7ypwkkiFcf12hta2m00)

See also some doc here:
- https://plantuml.com/nwdiag

_If that can help,_
Regards.

**Comment by arnaudroques** [comment]
Thanks for the feedback.

This is fixed [in last beta](https://github.com/plantuml/plantuml/releases/tag/snapshot) and [on the online server](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuSehJybCJ5UevifBBIdFByfMC3KmDD8DypKBrWi7YfPdffHaADWgf9Ncv70fA2Yaf9R5EmBfwCIKbABKucAWb19OJ4aX5YRlX27h19Aj1KA7rBmKeAq0).

**Comment by doczkal** [comment]
@arnaudroques I have pasted my minimal example from above and it still fails with an error.
![image](https://user-images.githubusercontent.com/16597855/149623377-47574752-24c2-4ca2-8672-3832b3467118.png)

If I remove dots and hyphens works.
![image](https://user-images.githubusercontent.com/16597855/149623421-b885c079-0a1a-4a68-a90a-bf64b006b8ff.png)
