### ISSUE TITLE
Issue to integrate image on diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#886]
Hello @arnaudroques,

Is it due to security protection, but all the examples on the doc. with image are broken, as:
```puml
@startuml
:
* Use image : <img:http://plantuml.com/logo3.png>
;
@enduml
```
>[![](http://www.plantuml.com/plantuml/svg/SoWkIImgAStDuRBYqb88BKvLoCnDJ4zLi5AmoSnDjyeeAIcmqjSlo4dC0odIIyxFrS_9JyytrYl8IxVZikPoICrB0Ke00000)](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuRBYqb88BKvLoCnDJ4zLi5AmoSnDjyeeAIcmqjSlo4dC0odIIyxFrS_9JyytrYl8IxVZikPoICrB0Ke00000)

from:
- https://plantuml.com/creole

Is it normal?

_[See also: [QA-15343](https://forum.plantuml.net/15343/mostly-getting-cannot-decode-image-error)]_
Regards.

**Comment by arnaudroques** [comment]
We had some certificate issues on the server.

It should be fixed now!

Sorry for the delay.

**Comment by maresh2all** [comment]
I seems like the exact same error is back as @The-Lum has described it. @arnaudroques, can you check if the certificate problem is back?

**Comment by The-Lum** [comment]
Hi @maresh2all, and all,

Just change `http` to `https` as:
```puml
@startuml
:
* Use image : <img:https://plantuml.com/logo3.png>
;
@enduml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuRBYqb88BKvLoCnDJ4zLi5AmoSnDjyeeAIaejjBNByX9p0EfqalEpzNFoK_FDzOho4ktuxBcSaZDIm5A0000)](https://www.planttext.com/?text=SoWkIImgAStDuRBYqb88BKvLoCnDJ4zLi5AmoSnDjyeeAIaejjBNByX9p0EfqalEpzNFoK_FDzOho4ktuxBcSaZDIm5A0000) 

_Enjoy,_
Regards,
Th.
